debuggerd: Resolve tombstoned missing O_CREAT mode
 debuggerd/tombstoned/tombstoned.cpp:115:92:
  error: 'openat' has superfluous mode bits; missing O_CREAT?
    unique_fd result(openat(dir_fd_, ".",
    O_WRONLY | O_APPEND | O_TMPFILE | O_CLOEXEC, 0640));

Change-Id: Iae787e477b7eab1f11c79f30c35fd6808959e38a

Former-commit-id: fd282689103cbd184eea3d718fbd093f8fd3cb6a
Former-commit-id: 98d41b311eed37983349fb0a58e3d5249e4ad827
Former-commit-id: d4c91a02074efb29b693c37d58eaeea638c1d58f
Former-commit-id: e86cbcf6aad0168a64ecb8aa29c99ed8a71534a7
Former-commit-id: 2aca14e988951fac57c1667d8c76d57f4ff247c0